### ISSUE TITLE
automate checksum check for easier updating coreos image

### ISSUE THREAD

**Issue by ikke-t** [RedHat-EMEA-SSA-Team/hetzner-ocp4#101]
I was about to install up to date version of OCP. I noticed the checksum comparison could be simpler.

Now one needs to download the coreos image, and unzip it and check the checksum manually, and put it back to ansible configs. There would already be checksum for the gzipped version of image at download site: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.4/4.4.3/sha256sum.txt

I suggest the following change, so that the checksum check can be made automatic, and no need for such manual steps and config changes:

1. if coreos gzip is donwloaded, download also the checksum file
2. verify the checksum of gzip file
3. gunzip the coreos
4. create new checksum of the current image, and store it as a file next to coreos image. e.g. ```{{ coreos_image_location }}.sha256.txt```
5. on later runs, if coreos image is found from system, just verify the csum against the file.

The steps 1-4 are only done if the coreos is not already found, but needs downloading.

This would remove the manual steps from process, and it would be easier to update the coreos versions.

**Comment by rbo** [comment]
That would check the checksum of the zip not of the actually qcow2 image. right?  The goal was to check the qcow2 checksum to avoid problems with the qcow2.

**Comment by ikke-t** [comment]
Nope, it would check them both. So first that the downloaded gzip is ok, and then after extracting, it would be made sure it stays like that, just like now.

**Comment by ikke-t** [comment]
Hmmm, I couldn't let this be, so I made a fix for it. This removes the need for manual checksum calculation, and get's rid of checksum variable in the cluster.yml. I'll fit it into playbooks later, I just made a schetch, proof of concept:

```
---

- name: download coreos
  hosts: all
  vars:
    coreos_version: 4.4.3
    coreos_download_url:
      "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/\
      {{ coreos_version.split('.')[:2]|join('.') }}/latest/\
      rhcos-{{ coreos_version }}-x86_64-qemu.x86_64.qcow2.gz"
    coreos_csum_url: "https://mirror.openshift.com/pub/openshift-v4/\
      dependencies/rhcos/{{ coreos_version.split('.')[:2]|join('.') }}/\
      latest/sha256sum.txt"
    coreos_file: rhcos-{{ coreos_version }}-x86_64-qemu.x86_64.qcow2
    coreos_path: /tmp
  tasks:

    - name: check if coreos image already downloaded and get checksum
      stat:
        checksum_algorithm: sha256
        path: "{{ coreos_path }}/{{ coreos_file }}"
      register: coreos_old_image

    - name: verify existing coreos image is valid
      lineinfile:
        name: "{{ coreos_path }}/{{ coreos_file }}.sha256.txt"
        line: "{{ coreos_old_image.stat.checksum }}  {{ coreos_file }}"
        state: present
      check_mode: true
      register: csum_check
      failed_when: (csum_check is changed) or (csum_check is failed)
      ignore_errors: true
      when: coreos_old_image.stat.exists

    - name: Download fresh coreos image if previous doesn't exist
      block:

        - name: download coreos
          get_url:
            url: "{{ coreos_download_url }}"
            dest: "{{ coreos_path }}/{{ coreos_file }}.gz"
            checksum: "sha256:{{ coreos_csum_url }}"
          register: coreos_download

        - name: unzip the coreos
          command: "gunzip {{ coreos_path }}/{{ coreos_file }}.gz"
          args:
            chdir: "{{ coreos_path }}"
            creates: "{{ coreos_path }}/{{ coreos_file }}"
          register: unzip

        - name: calculate checksum of the new coreos image
          stat:
            checksum_algorithm: sha256
            path: "{{ coreos_path }}/{{ coreos_file }}"
          register: coreos_csum

        - name: store the checksum of the file
          copy:
            dest: "{{ coreos_path }}/{{ coreos_file }}.sha256.txt"
            content: "{{ coreos_csum.stat.checksum }}  {{ coreos_file }}\n"

      when: >
        (not coreos_old_image.stat.exists) or
        csum_check.changed or
        csum_check.failed
```

This one download the image only if the stored checksum doesn't match. While downloading, it verifies the checksum of the downloaded image before unzip. After unzip it stores the checksum in automated way this time. So image validity should be 100%.
