### ISSUE TITLE
Looks like qemu-img version 6.1.0 needs "-F" parameter

### ISSUE THREAD

**Issue by goetzrieger** [RedHat-EMEA-SSA-Team/hetzner-ocp4#200]
Couldn't deploy on a CentOS 8 Stream Hetzner server with latest updates because creating the images with qemu failed.

Looks like at least in qemu-img 6.1.0 the "-F" for target format is needed. I didn't hand in a PR because I don't know if this would break older qemu-img versions...

So in `ansible/roles/openshift-4-cluster/tasks/create-vm.yml` I changed

```
- name: Create disk for {{ vm_instance_name }}
  command: "qemu-img create -f qcow2 -b {{ coreos_image_location }} /var/lib/libvirt/images/{{ vm_instance_name }}.qcow2 {{ vm_root_disk_size }}"
  args:
    creates: "/var/lib/libvirt/images/{{ vm_instance_name }}.qcow2"
  when: vm_storage_backend == "qcow2"
```

to

```
- name: Create disk for {{ vm_instance_name }}
  command: "qemu-img create -f qcow2 -F qcow2 -b {{ coreos_image_location }} /var/lib/libvirt/images/{{ vm_instance_name }}.qcow2 {{ vm_root_disk_size }}"
  args:
    creates: "/var/lib/libvirt/images/{{ vm_instance_name }}.qcow2"
  when: vm_storage_backend == "qcow2"
```

And all is well... ;)
