### ISSUE TITLE
pure-ansible: Create & Use an ssa cluster configuration operator

### ISSUE THREAD

**Issue by rbo** [RedHat-EMEA-SSA-Team/hetzner-ocp4#21]
Replace the ansible post-installation with an operator

Be careful with ssl cert and ` lookup('file'` because it strips the last important \n:
```yaml
- name: Check certificates exist
  stat:
    path: "{{ ign_certificates_path }}/fullchain.crt"
  register: crt
- name: Check ssl key exist
  stat:
    path: "{{ ign_certificates_path }}/cert.key"
  register: key

- name: Create openshift-ingress config
  block:
    - name: Create openshift router certs secret
      copy:
        content: |
          apiVersion: v1
          kind: Secret
          data:
            tls.crt: {{  lookup('file',ign_certificates_path + '/fullchain.crt', rstrip=false) | b64encode }}
            tls.key: {{  lookup('file',ign_certificates_path + '/cert.key', rstrip=false)  | b64encode }}
          metadata:
            name: letsencrypt-router-certs
            namespace: openshift-ingress
          type: kubernetes.io/tls
        dest: "{{ ign_openshift_install_dir }}/openshift/99_openshift-ingress-letsencrypt-router-certs-secret.yaml"

  when: crt.stat.exists == True and key.stat.exists == True
```
