### ISSUE TITLE
Include user list to cluster.yml

### ISSUE THREAD

**Issue by tahonen** [RedHat-EMEA-SSA-Team/hetzner-ocp4#24]
cluster.yml should have list of users which are added to htpasswd secret for htpasswd based auth. Also one of those users should be labeled cluster-admin.

**Comment by tahonen** [comment]
Something like this
```
users:
- user1:pass1
- user2:pass2
cluster_admin: user1
```

**Comment by rbo** [comment]
> Something like this
> 
> ```
> cluster_admin: user1
> ```

I did the same in my cluster operator, but I think something is better and more flexible:
```yaml
cluster_role_binding:
- cluster_role: cluster-admin
  username: user1
- cluster_role: sudoer
  username: user2
```
