### ISSUE TITLE
IPv6 only - /etc/hosts entry wrong

### ISSUE THREAD

**Issue by rbo** [RedHat-EMEA-SSA-Team/hetzner-ocp4#319]
```
[root@pluto mirror]# virsh net-dumpxml demo
<network ipv6='yes'>
  <name>demo</name>
  <uuid>83811258-b28c-47ca-8886-782cd4fd6f5e</uuid>
  <forward mode='open'/>
  <bridge name='virbr1' stp='on' delay='0'/>
  <mac address='52:54:00:36:1b:26'/>
  <domain name='compute.local'/>
  <dns>
    <host ip='2a01:4f9:4a:3355:32::1'>
      <hostname>host.compute.local</hostname>
      <hostname>api-int.demo.openshift.pub</hostname>
      <hostname>api.demo.openshift.pub</hostname>
      <hostname>oauth-openshift.apps.demo.openshift.pub</hostname>
      <hostname>console-openshift-console.apps.demo.openshift.pub</hostname>
    </host>
  </dns>
  <ip family='ipv6' address='2a01:4f9:4a:3355:32::1' prefix='80'>
    <dhcp>
      <range start='2a01:4f9:4a:3355:32::1000' end='2a01:4f9:4a:3355:32::2000'/>
      <host id='00:03:00:01:52:54:00:a8:32:02' name='bootstrap.compute.local' ip='2a01:4f9:4a:3355:32::2'/>
      <host id='00:03:00:01:52:54:00:a8:32:0a' name='master-0.compute.local' ip='2a01:4f9:4a:3355:32::1000'/>
      <host id='00:03:00:01:52:54:00:a8:32:0b' name='master-1.compute.local' ip='2a01:4f9:4a:3355:32::1001'/>
      <host id='00:03:00:01:52:54:00:a8:32:0c' name='master-2.compute.local' ip='2a01:4f9:4a:3355:32::1002'/>
    </dhcp>
  </ip>
</network>

[root@pluto mirror]# cat /etc/hosts 
### Hetzner Online GmbH installimage
127.0.0.1 localhost.localdomain localhost
95.217.117.251 95.217.117.251 95
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
2a01:4f9:4a:3355::2 95.217.117.251 95
# BEGIN ANSIBLE MANAGED BLOCK demo.openshift.pub
95.217.117.251 api.demo.openshift.pub
# END ANSIBLE MANAGED BLOCK demo.openshift.pub
192.168.50.1 host.compute.local
[root@pluto mirror]# 
```

**Comment by rbo** [comment]
By default podman run's only with IPv4. To change this:

Enable IPv6 at podman network
```
podman network create --ipv6 --gateway fd00::1:8:1 --subnet fd00::1:8:0/112 --gateway 10.90.0.1 --subnet 10.90.0.0/16 podman1

sudo cp /usr/share/containers/containers.conf /etc/containers/
# change default network
vim /etc/containers/containers.conf
diff -Nuar /usr/share/containers/containers.conf /etc/containers/containers.conf 
--- /usr/share/containers/containers.conf       2024-04-18 10:30:44.000000000 +0200
+++ /etc/containers/containers.conf     2024-06-30 16:10:23.516423665 +0200
@@ -342,7 +342,7 @@
 
 # The network name of the default network to attach pods to.
 #
-#default_network = "podman"
+default_network = "podman1"
 
 # The default subnet for the default network given in default_network.
 # If a network with that name does not exist, a new network using that name and
```

Change quay mirror registry listen config
```
mkdir executionvars
mv execution-environment.tar executionvars/
cd executionvars
tar xvf execution-environment.tar
# Add FEATURE_LISTEN_IP_VERSION: dual-stack  
# or
# FEATURE_LISTEN_IP_VERSION: IPv6
vim runner/project/roles/mirror_appliance/templates/config.yaml.j2


tar cvjf execution-environment.tar ./*
mv execution-environment.tar ../

```


Resources:
* <https://developers.redhat.com/articles/2022/08/10/how-conifgure-podman-40-ipv6#create_an_interface_that_supports_the_dual_ipv4_ipv6_stack>
* <https://access.redhat.com/solutions/7058326>

**Comment by rbo** [comment]
I don't get DHCPv6 running, let's try agent base installer with static ipv6

<details>
  <summary>agent-config.yaml</summary>

```yaml

apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: demo
rendezvousIP: 2a01:4f9:4a:3355:32::1000
hosts:
  - hostname: master-0
    interfaces:
      - name: eno1
        macAddress: 52:54:00:a8:32:0a
    networkConfig:
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          mac-address: 52:54:00:a8:32:0a
          ipv6:
            enabled: true
            address:
              - ip: 2a01:4f9:4a:3355:32::1000
                prefix-length: 80
            dhcp: false
          ipv4:
            enabled: false
      dns-resolver:
        config:
          server:
            - 2a01:4f9:4a:3355:32::1
      routes:
        config:
          - destination: ::/0
            next-hop-address: 2a01:4f9:4a:3355:32::1
            next-hop-interface: eno1
            table-id: 254
  - hostname: master-1
    interfaces:
      - name: eno1
        macAddress: 52:54:00:a8:32:0b
    networkConfig:
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          mac-address: 52:54:00:a8:32:0b
          ipv6:
            enabled: true
            address:
              - ip: 2a01:4f9:4a:3355:32::1001
                prefix-length: 80
            dhcp: false
          ipv4:
            enabled: false
      dns-resolver:
        config:
          server:
            - 2a01:4f9:4a:3355:32::1
      routes:
        config:
          - destination: ::/0
            next-hop-address: 2a01:4f9:4a:3355:32::1
            next-hop-interface: eno1
            table-id: 254
  - hostname: master-0
    interfaces:
      - name: eno1
        macAddress: 52:54:00:a8:32:0c
    networkConfig:
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          mac-address: 52:54:00:a8:32:0c
          ipv6:
            enabled: true
            address:
              - ip: 2a01:4f9:4a:3355:32::1002
                prefix-length: 80
            dhcp: false
          ipv4:
            enabled: false
      dns-resolver:
        config:
          server:
            - 2a01:4f9:4a:3355:32::1
      routes:
        config:
          - destination: ::/0
            next-hop-address: 2a01:4f9:4a:3355:32::1
            next-hop-interface: eno1
            table-id: 254
```

</details>


firewalld rules are not applied to IPv6 🤷🏻‍♀️

```
systemctl stop firewalld.service
```
