### ISSUE TITLE
Update to 4.3.9 or 4.3.10 will fail

### ISSUE THREAD

**Issue by tjungbauer** [RedHat-EMEA-SSA-Team/hetzner-ocp4#96]
Hello,

The update to 4.3.9+ will fail with:

`E0413 16:21:53.310311       1 sync_worker.go:329] unable to synchronize image (waiting 2m52.525702462s): Precondition "ClusterVersionUpgradeable" failed because of "DefaultSecurityContextConstraints_Mutated": Cluster operator kube-apiserver cannot be upgraded: DefaultSecurityContextConstraintsUpgradeable: Default SecurityContextConstraints object(s) have mutated [hostmount-anyuid]`

as also discussed here: https://bugzilla.redhat.com/show_bug.cgi?id=1818893 

The reason is the custom user for hostmount-anyuid: system:serviceaccount:openshift-nfs-provisioner:nfs-client-provisioner

The solution seems to be to clone the default SCC and put the changes there.

**Comment by tahonen** [comment]
I have been running 4.4 from rc4 and updates have been working ok. Have update to rc-5 and rc-6 and rc-7. If you feel lucky try updating directly to 4.4-rc7 `quay.io/openshift-release-dev/ocp-release@sha256:df3b7a74c8590a932c00fd9b1ef6c1fb2a0bfd1c3643b78ae378cadee3258c03`

**Comment by tjungbauer** [comment]
hmm, according to the bugzilla 4.4 will stomp any changes in the default SCCs. So maybe the nfs-provisioner is not added in your config anymore, or you have already a custom/cloned
 SCC

**Comment by tahonen** [comment]
Running 4.4rc8 now it is working file.
```
[root@host01 ~]# oc describe scc hostmount-anyuid
Name:						hostmount-anyuid
Priority:					<none>
Access:						
  Users:					system:serviceaccount:openshift-infra:pv-recycler-controller,system:serviceaccount:openshift-nfs-provisioner:nfs-client-provisioner
  Groups:					<none>
Settings:					
...
```

**Comment by tjungbauer** [comment]
I have this:
`users:
- system:serviceaccount:openshift-nfs-provisioner:nfs-client-provisioner`

The user was added during the ansible deployment and above error complains about changes in the default SCC.
When I cloned it (as hostmount-anyuid-custom) and removed it from the default one, it worked. 

btw: I installed the cluster with storage_nfs: true
So this task will one add the user to the SCC when storage_nfs is set to true.

**Comment by rbo** [comment]
😳 - let's wait of [BZ 1818893](https://bugzilla.redhat.com/show_bug.cgi?id=1818893) to check out what is the right solution. 

I don't understand the work-a-round in [Comment 8](https://bugzilla.redhat.com/show_bug.cgi?id=1818893#c8):

> A workaround to "adding an account to any SCC" is to use RBAC to give a user access to the default SCC. This way the customer can avoid changing the default SCC.

It's good to check the SCC bevor upgrade, but not the members. I don't like to create a copy of `hostmount-anyuid`  scc.

**Comment by rbo** [comment]
**Solution:**
1) Remove scc member: 
```
oc adm policy remove-scc-from-user hostmount-anyuid system:serviceaccount:openshift-nfs-provisioner:nfs-client-provisioner
```
2) Add RBAC to allow nfs-provision to run with hostmount-anyuid:
```
oc create -f - <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-hostmount-anyuid
  namespace: "openshift-nfs-provisioner"
rules:
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - hostmount-anyuid
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-to-scc-hostmount-anyuid
  namespace: "openshift-nfs-provisioner"
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner
roleRef:
  kind: Role
  name: scc-hostmount-anyuid
  apiGroup: rbac.authorization.k8s.io
EOF
```

PR for new installation will follow or highly appreciated :-)

**Comment by tfriman** [comment]
@rbo Should this fix work as is?

**Comment by rbo** [comment]
@tfriman  Yes, tested at my cluster

**Comment by tfriman** [comment]
Ok, it doesn't work on mine (4.3.8 and .9/.10/.12/.13 all fail) but maybe I'll fix mine with reinstall anyways :-)

**Comment by rbo** [comment]
Please check the log of CVO pod. The fix solve only the nfs provisioner. If you install openshift pipeline (for example) then opeshift pipeline is the problem for failing cluster update.

**Comment by tfriman** [comment]
Ah, I have installed plenty of operators (also pipelines).

Cluster version operator log says:

````E0420` 15:29:46.764643       1 precondition.go:49] Precondition "ClusterVersionUpgradeable" failed: Cluster operator kube-apiserver cannot be upgraded: DefaultSecurityContextConstraintsUpgradeable: Default SecurityContextConstraints object(s) have mutated [privileged]`````

**Comment by tjungbauer** [comment]
What I do not get, but maybe thats more for the bug to track, when you install for example the pipeline operator, the SCC will be modifed. With 4.4 they say any change will be stomped

**Comment by rbo** [comment]
> Ah, I have installed plenty of operators (also pipelines).
> 
> Cluster version operator log says:
> 
> `E0420 15:29:46.764643 1 precondition.go:49] Precondition "ClusterVersionUpgradeable" failed: Cluster operator kube-apiserver cannot be upgraded: DefaultSecurityContextConstraintsUpgradeable: Default SecurityContextConstraints object(s) have mutated [privileged]`

Please compare your privileged scc with the default of 4.3:
```
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- "*"
allowedUnsafeSysctls:
- "*"
apiVersion: security.openshift.io/v1
defaultAddCapabilities:
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
- system:nodes
- system:masters
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: 'privileged allows access to all privileged and host
      features and the ability to run as any user, any group, any fsGroup, and with
      any SELinux context.  WARNING: this is the most relaxed SCC and should be used
      only for cluster administration. Grant with caution.'
  name: privileged
priority:
readOnlyRootFilesystem: false
requiredDropCapabilities:
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- "*"
supplementalGroups:
  type: RunAsAny
users:
- system:admin
- system:serviceaccount:openshift-infra:build-controller
volumes:
- "*"
```
Source: https://bugzilla.redhat.com/show_bug.cgi?id=1821905
